### ISSUE TITLE
Use short array syntax

### ISSUE THREAD

**Issue by ins0** [EvanDotPro/EdpGithub#28]
as the travis build targets php version 4 and 5 i think it is safe to use the short array syntax in this repo?! no? 

//cc @EvanDotPro @Hounddog

**Comment by EvanDotPro** [comment]
Some factors to consider:

Packagist stats:
```
Overall: 1,159 installs
30 days: 270 installs
Today: 10 installs
```

We've had `"php": ">=5.3.3"` in composer.json since the beginning.

I think it's fair to assume that developers relied on the composer requirements rather than looking to see what versions the travis builds covers (which _should_ cover all versions in compser.json).

Conclusion: There's likely _some_ number of 5.3 applications in the wild that are already built around this module that will break. Maybe 10. Maybe 2. Maybe 0.

So, I guess it depends on how sympathetic you're feeling, and how badly you want those short arrays. :smile:

Honestly, I don't have a strong opinion on this at all, so I'll happily roll with the majority opinion.

**Comment by gianarb** [comment]
@ins0 In my opinion the short array syntax is not a good way to lose the 5.3 version :skull:

**Comment by ins0** [comment]
yeah wasn't thinking about this
